project_id = "adurodjrvnmfonqkifvm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"
max_header_length = 4096

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.image_transformation]
enabled = true

[auth]
enabled = true
site_url = "http://127.0.0.1:54321"
additional_redirect_urls = ["https://127.0.0.1:54321"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
email.enable_signup = true
email.enable_confirmations = false
sms.enable_signup = true
sms.enable_confirmations = false
external.google.enabled = true
external.google.client_id = ""
external.google.redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"
external.google.skip_nonce_check = false

[auth.email]
enable_confirmations = false

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.chat-with-ai]
verify_jwt = true