// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adurodjrvnmfonqkifvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkdXJvZGpydm5tZm9ucWtpZnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDc2MTcsImV4cCI6MjA3MjU4MzYxN30.aYR5qVD-dVzN5U_pWCzV4F7zbFpuUi971MJ0lu1TffQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});